config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'homepage/index'
  get 'flights/select/:id' => 'flights#search'
  get 'flights/:from/:to' => 'flights#destination'
  get 'reservations/select/:flight_id' => 'reservations#search'
  get 'reservations/booking/:booking_code' => 'reservations#booking'
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord

belongs_to :airplane, optional: true
has_many :reservations

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, raise: false

  # GET /flights
  # GET /flights.json
  def index
    headers['Access-Control-Allow-Origin'] = '*'
    respond_to do |format|
      format.html { render index: @flights = Flight.all  }
      format.json { render json: Flight.all , include: ['airplane'] }
    end
    # render json: Airplane.all
  end

  #GET flights/select/:id
  def search
    headers['Access-Control-Allow-Origin'] = '*'
    render json: set_flight, include: ['airplane']
  end

  # GET /flights/1
  # GET /flights/1.json
  def show

  end

  def destination
    headers['Access-Control-Allow-Origin'] = '*'
    render json: Flight.where(from:params[:from],to:params[:to]), include: ['airplane']
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:flight_no, :date, :to, :from, :airplane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_no %>
    <%= form.text_field :flight_no %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= form.text_field :from %>
  </div>

  <div class="field">
    <%= form.label :airplane_id %>
    <%= form.number_field :airplane_id %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>

app/views/flights/edit.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
    <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>Editing Flight</h1>

    <%= render 'form', flight: @flight %>

    <%= link_to 'Show', @flight, class: "btn btn-primary" %>
    <%= link_to 'Back', flights_path, class: "btn btn-danger" %>
  </div>


  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/flights/index.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center table">
    <p id="notice"><%= notice %></p>

    <h1>Flights</h1>

    <table>
      <thead>
        <tr>
          <th>Flight no</th>
          <th>Date</th>
          <th>To</th>
          <th>From</th>
          <th>Airplane</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @flights.each do |flight| %>
          <tr>
            <td><%= flight.flight_no %></td>
            <td><%= flight.date %></td>
            <td><%= flight.to %></td>
            <td><%= flight.from %></td>
            <td><%= flight.airplane_id %></td>
            <td><%= link_to 'Show', flight, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_flight_path(flight), class: "btn btn-success" %></td>
            <td><%= link_to 'Destroy', flight, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Flight', new_flight_path, class: "btn btn-success" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/flights/new.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>New Flight</h1>

    <%= render 'form', flight: @flight %>

    <%= link_to 'Back', flights_path %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/flights/show.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Flight no:</strong>
      <%= @flight.flight_no %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @flight.date %>
    </p>

    <p>
      <strong>To:</strong>
      <%= @flight.to %>
    </p>

    <p>
      <strong>From:</strong>
      <%= @flight.from %>
    </p>

    <p>
      <strong>Airplane:</strong>
      <%= @flight.airplane_id %>
    </p>

    <%= link_to 'Edit', edit_flight_path(@flight), class: "btn btn-success" %>
    <%= link_to 'Back', flights_path, class: "btn btn-danger" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>