config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'homepage/index'
  get 'flights/select/:id' => 'flights#search'
  get 'flights/:from/:to' => 'flights#destination'
  get 'reservations/select/:flight_id' => 'reservations#search'
  get 'reservations/booking/:booking_code' => 'reservations#booking'
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord

has_many :flights

end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    headers['Access-Control-Allow-Origin'] = '*'
    respond_to do |format|
      format.html { render index: @airplanes = Airplane.all  }
      format.json { render json: Airplane.all }
    end
    # render json: Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airplane_params
      params.require(:airplane).permit(:serial_no, :row, :column)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_with(model: airplane, local: true) do |form| %>
  <% if airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :serial_no %>
    <%= form.number_field :serial_no %>
  </div>

  <div class="field">
    <%= form.label :row %>
    <%= form.number_field :row %>
  </div>

  <div class="field">
    <%= form.label :column %>
    <%= form.number_field :column %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/airplanes/edit.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
    <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>Editing Airplane</h1>

    <%= render 'form', airplane: @airplane %>

    <%= link_to 'Show', @airplane, class: "btn btn-primary" %>
    <%= link_to 'Back', airplanes_path, class: "btn btn-danger" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/airplanes/index.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
    <%= render partial: 'layouts/nav'%>
  </nav>
  <p id="notice"><%= notice %></p>

  <div class="text-center">
    <h1>Airplanes</h1>

    <table class="text-center table">
      <thead>
        <tr>
          <th>Serial no</th>
          <th>Row</th>
          <th>Column</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @airplanes.each do |airplane| %>
          <tr>
            <td><%= airplane.serial_no %></td>
            <td><%= airplane.row %></td>
            <td><%= airplane.column %></td>
            <td><%= link_to 'Show', airplane, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_airplane_path(airplane), class: "btn btn-success" %></td>
            <td><%= link_to 'Destroy', airplane, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Airplane', new_airplane_path, class: "btn btn-success" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/airplanes/new.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
    <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>New Airplane</h1>

    <%= render 'form', airplane: @airplane %>

    <%= link_to 'Back', airplanes_path %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/airplanes/show.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
    <%= render partial: 'layouts/nav'%>
  </nav>

<div class="text-center">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Serial no:</strong>
      <%= @airplane.serial_no %>
    </p>

    <p>
      <strong>Row:</strong>
      <%= @airplane.row %>
    </p>

    <p>
      <strong>Column:</strong>
      <%= @airplane.column %>
    </p>

    <%= link_to 'Edit', edit_airplane_path(@airplane), class: "btn btn-success" %>
    <%= link_to 'Back', airplanes_path, class: "btn btn-danger" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>