config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'homepage/index'
  get 'flights/select/:id' => 'flights#search'
  get 'flights/:from/:to' => 'flights#destination'
  get 'reservations/select/:flight_id' => 'reservations#search'
  get 'reservations/booking/:booking_code' => 'reservations#booking'
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reservations
  has_many :flights, through: :reservation

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    headers['Access-Control-Allow-Origin'] = '*'
    respond_to do |format|
      format.html { render index: @users = User.all  }
      format.json { render json: User.all }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :email %>
    <%= form.text_field :email %>
    <br>

    <%= form.label :password %>
    <%= form.password_field :password %>
    <br>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user, class: "btn btn-primary" %>
    <%= link_to 'Back', users_path, class: "btn btn-danger" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <p id="notice"><%= notice %></p>

    <h1>Users</h1>

    <table class="text-center table">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-success" %></td>
            <td><%= link_to 'Destroy', user, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, class: "btn btn-success" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <h1>New User</h1>

    <%= render 'form', user: @user %>


    <%= link_to 'Back', users_path %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="text-center">
    <%= image_tag 'logo.jpg', size: "100x100", class: "inline-image" %>
    <h2 class="inline-image">Burning Airlines - Admin</h2>
  </div>
  <nav>
      <%= render partial: 'layouts/nav'%>
  </nav>

  <div class="text-center">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-success" %>
    <%= link_to 'Back', users_path, class: "btn btn-danger" %>
  </div>

  <footer>
    &copy; 2021 Burning Airlines
  </footer>
</div>