config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get 'homepage/index'
  get 'flights/select/:id' => 'flights#search'
  get 'flights/:from/:to' => 'flights#destination'
  get 'reservations/select/:flight_id' => 'reservations#search'
  get 'reservations/booking/:booking_code' => 'reservations#booking'
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<div class="btn-group special" role="group">
  <%= link_to "Airplanes", airplanes_path, class: "btn btn-secondary"%>
  <%= link_to "Flights", flights_path, class: "btn btn-secondary"%>
  <%= link_to "Reservations", reservations_path, class: "btn btn-secondary"%>
  <%= link_to "Users", users_path, class: "btn btn-secondary"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <title>Hello, world!</title>
  </head>
  <body>
    <% if @current_user.present? %>
          <li><%= link_to "Logout", login_path, method: 'delete'%></li>
        <% else %>
          <li><%= link_to "Login", login_path  %></li>
        <% end %>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>